### ISSUE TITLE
AssertionError when using hocr-pdf

### ISSUE THREAD

**Issue by pprw** [stefan6419846/hocr-tools#30]
After 

`pip install hocr-tools-lib `

or 

`pip install git+https://github.com/stefan6419846/hocr-tools.git --force`

I have an AssertionError when launching hocr-pdf

 ```
$ hocr-pdf . > output.pdf 
Traceback (most recent call last):
  File "/home/pierre/.venvs/hocr/bin/hocr-pdf", line 8, in <module>
    sys.exit(main())
             ^^^^^^
  File "/home/pierre/.venvs/hocr/lib/python3.11/site-packages/hocr_tools_lib/tools/hocr_pdf.py", line 215, in main
    export_pdf(directory=args.imgdir, default_dpi=300, savefile=args.savefile)
  File "/home/pierre/.venvs/hocr/lib/python3.11/site-packages/hocr_tools_lib/tools/hocr_pdf.py", line 96, in export_pdf
    add_text_layer(pdf, image, height, dpi)
  File "/home/pierre/.venvs/hocr/lib/python3.11/site-packages/hocr_tools_lib/tools/hocr_pdf.py", line 122, in add_text_layer
    assert baseline_match is not None
           ^^^^^^^^^^^^^^^^^^^^^^^^^^
AssertionError

```

**Comment by stefan6419846** [comment]
Oops, I slightly remember that the hOCR files generated by *kraken* would not pass directly, although I unfortunately did not record the changes I evaluated for testing some time ago.

I have just fixed the error you got on GitHub and hope that this has been the only issue. A corresponding self-test will be added later.

**Comment by stefan6419846** [comment]
Re-opening for now. Otherwise I will forget (again) to add a corresponding test.
